'use client';

import {
  Bell,
  Briefcase,
  Buildings,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  Check,
  CheckCircle,
  Circle,
  Clock,
  Copy,
  DotsThreeVertical,
  Envelope,
  Eye,
  EyeSlash,
  Gear,
  Globe,
  House,
  IdentificationCard,
  Key,
  Link as LinkIcon,
  List,
  LinkBreak,
  MagnifyingGlass,
  MapPin,
  Moon,
  PencilSimple,
  Phone,
  Plus,
  Prohibit,
  ShieldCheck,
  SidebarSimple,
  SignOut,
  SquaresFour,
  Sun,
  Trash,
  User,
  UserCircle,
  UserCirclePlus,
  Users,
  Warning,
  WarningCircle,
  X,
} from '@phosphor-icons/react';
import type { ComponentProps } from 'react';

export const Icons = {
  home: House,
  settings: Gear,
  notifications: Bell,
  user: User,
  userCircle: UserCircle,
  userPlus: UserCirclePlus,
  users: Users,
  dashboard: SquaresFour,
  logout: SignOut,
  menu: List,
  close: X,
  left: CaretLeft,
  right: CaretRight,
  down: CaretDown,
  globe: Globe,
  sun: Sun,
  moon: Moon,
  sidebarSimple: SidebarSimple,
  buildings: Buildings,
  briefcase: Briefcase,
  shieldCheck: ShieldCheck,
  link: LinkIcon,
  linkBreak: LinkBreak,
  copy: Copy,
  plus: Plus,
  search: MagnifyingGlass,
  ban: Prohibit,
  check: Check,
  checkCircle: CheckCircle,
  circle: Circle,
  warning: Warning,
  warningCircle: WarningCircle,
  mail: Envelope,
  phone: Phone,
  mapPin: MapPin,
  idCard: IdentificationCard,
  key: Key,
  clock: Clock,
  calendar: CalendarBlank,
  edit: PencilSimple,
  trash: Trash,
  moreVertical: DotsThreeVertical,
  eye: Eye,
  eyeOff: EyeSlash,
} as const;

export type IconName = keyof typeof Icons;

interface IconProps extends Omit<ComponentProps<typeof House>, 'name'> {
  name: IconName;
}

export function Icon({ name, ...props }: IconProps) {
  const Cmp = Icons[name];
  return <Cmp {...props} />;
}
